#!/usr/bin/env bash
#
# refresh-cloudflare-ips.sh — teach nginx which address the visitor actually has.
#
# WHAT THIS FIXES, because it is not obvious from the symptom.
#
# With Cloudflare in front of the origin, $remote_addr is the EDGE NODE that
# relayed the request, and it is a different node from one request to the next.
# Every rate limiter in this application is keyed on the client IP — public
# appointment requests, contact-us, family sign-in, member sign-in, unsubscribe —
# so each of them was bucketing by edge rather than by person. Two consequences,
# and the second is the one that would have reached a real user:
#
#   1. A flood spread itself across dozens of buckets, so a cap of 8 per hour
#      let through far more than 8. Measured on staging before this landed:
#      twelve identical submissions, one 429.
#   2. Two unrelated visitors who happened to share an edge node shared a
#      bucket, so a stranger's requests could lock a real person out of a
#      sign-in form.
#
# WHY ONLY CLOUDFLARE'S RANGES ARE TRUSTED. This origin also answers requests
# that did not come through Cloudflare. Trusting every proxy would let any of
# those callers send CF-Connecting-IP and choose the address the application
# sees — which would hand an attacker the ability to evade every limiter and to
# write whatever they liked into the access log.
#
# WHY NGINX AND NOT Laravel's TrustProxies: fixing it here also fixes the access
# log, which is where this project has repeatedly gone first when debugging a
# live problem. A log full of edge IPs is a log that cannot answer "who did
# this?".
#
# Run it on a box after Cloudflare publishes a new range. It validates before it
# reloads and puts the old file back if the new one does not parse.
set -euo pipefail

CONF=/etc/nginx/conf.d/cloudflare-realip.conf
BACKUP="${CONF}.bak-$(date -u +%Y%m%d-%H%M%S)"

V4=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)
V6=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)
[ -n "$V4" ] && [ -n "$V6" ] || { echo "could not fetch Cloudflare's ranges — nothing changed"; exit 1; }

[ -f "$CONF" ] && cp -p "$CONF" "$BACKUP"

{
    echo "# Generated by deploy/nginx/refresh-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# Do not hand-edit: the ranges are fetched from Cloudflare, because a"
    echo "# stale hand-copied list is how this silently stops working."
    echo
    for r in $V4 $V6; do echo "set_real_ip_from $r;"; done
    echo
    echo "real_ip_header CF-Connecting-IP;"
} > "$CONF"

if nginx -t; then
    systemctl reload nginx
    echo "nginx reloaded with $(grep -c set_real_ip_from "$CONF") Cloudflare ranges"
else
    if [ -f "$BACKUP" ]; then cp -p "$BACKUP" "$CONF"; else rm -f "$CONF"; fi
    nginx -t
    echo "REVERTED — the generated config did not validate"
    exit 1
fi
