// This type used to ensure the validation of back-end API routes
export type BackendApiRoute =
    '/api/admin/login' |
    '/api/admin/user' |
    '/api/admin/masjids' |
    '/api/admin/logout' |
    `/api/admin/masjids/${string}/` |
    `/api/admin/masjids/${string}/search?search_for=${string}` |
    `/api/admin/masjids/${string}/details` |
    `/api/admin/masjids/${string}/announcements` |
    `/api/admin/masjids/${string}/announcements?page=${number}` |
    `/api/admin/masjids/${string}/announcements/${string}/` |
    `/api/admin/masjids/${string}/announcements/${string}/trash` |
    `/api/admin/masjids/${string}/splash-announcements` |
    `/api/admin/masjids/${string}/splash-announcements?page=${number}` |
    `/api/admin/masjids/${string}/splash-announcements/${string}` |
    `/api/admin/masjids/${string}/splash-announcements/${string}/trash` |
    `/api/admin/masjids/${string}/events` |
    `/api/admin/masjids/${string}/events?page=${number}` |
    `/api/admin/masjids/${string}/events/${string}/` |
    `/api/admin/masjids/${string}/services` |
    `/api/admin/masjids/${string}/services?page=${number}` |
    `/api/admin/masjids/${string}/services/${string}/` |
    `/api/admin/masjids/${string}/services/${string}/trash` |
    `/api/admin/masjids/${string}/contacts` |
    `/api/admin/masjids/${string}/contacts?page=${number}` |
    `/api/admin/masjids/${string}/contacts/${string}` |
    `/api/admin/masjids/${string}/funds` |
    `/api/admin/masjids/${string}/funds/${string}` |
    `/api/admin/masjids/${string}/donations` |
    `/api/admin/masjids/${string}/donations?page=${number}` |
    `/api/admin/masjids/${string}/donations/${string}` |
    `/api/admin/masjids/${string}/donation-link` |
    `/api/admin/masjids/${string}/about` |
    `/api/admin/masjids/${string}/gallery` |
    `/api/admin/masjids/${string}/gallery/${string}` |
    `/api/admin/hadiths` |
    `/api/admin/hadiths/${string}/` |
    `/api/admin/hadiths?page=${number}` |
    `/api/admin/hadiths/library` |
    `/api/admin/hadiths/library?search=${string}` |
    `/api/admin/hadiths/library/add` |
    `/api/admin/masjids/${string}/features` |
    `/api/admin/masjids/${string}/features/${string}/` |
    `/api/admin/masjids/${string}/crm-access` |
    `/api/admin/masjids/${string}/assistant-access` |
    `/api/admin/masjids/${string}/assistant/chat` |
    `/api/admin/masjids/${string}/iqama` |
    `/api/admin/masjids/${string}/jumaa` |
    `/api/admin/masjids/${string}/theme` |
    `/api/admin/masjids/${string}/notifications` |
    `/api/admin/azkar` |
    `/api/admin/azkar/${string}/` |
    `/api/admin/azkar?page=${number}` |
    `/api/admin/azkar/categories` |
    `/api/admin/azkar/library` |
    `/api/admin/azkar/library?search=${string}` |
    `/api/admin/azkar/library/add` |
    `/api/admin/tasabih` |
    `/api/admin/tasabih/${string}/` |
    `/api/admin/tasabih?page=${number}` |
    `/api/admin/tasabih/library` |
    `/api/admin/tasabih/library?search=${string}` |
    `/api/admin/tasabih/library/add` |
    '/api/admin/admins/masjid/available' |
    '/api/admin/countries' |
    `/api/admin/countries/${number}/cities` |
    `/api/admin/masjids/${number}` |
    `/api/admin/masjids/${string}/trash` |
    `/api/admin/users` |
    `/api/admin/users/${string}/` |
    `/api/admin/users/${string}/trash` |
    `/api/admin/profile` |
    `/api/admin/app-config` |
    `/api/admin/app-config/${string}` |
    `/api/admin/search?search_for=${string}`
